version: '1.0'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '5000'
    ports:
      - '5000:5000'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: 'always'
    command: yarn run dev